# Generated by Django 3.1.6 on 2021-02-19 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210219_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renion',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.renionstatus'),
        ),
    ]
